name = "mc-discord-bot"
main = "worker.js"
compatibility_date = "2024-09-01"

# Sửa lại thành "tenGitHub/tenRepo" của bạn
[vars]
GH_REPO = "ten-tai-khoan/ten-repo"

# 2 secret còn lại KHÔNG khai báo ở đây, set bằng lệnh:
#   wrangler secret put DISCORD_PUBLIC_KEY
#   wrangler secret put GH_TOKEN
